name: GCC

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install tools
      run: |
        sudo apt update
        sudo apt --yes install clang cmake ninja-build
        sudo apt --yes install libgtk-3-dev

    - name: Build
      run: |
        mkdir out
        cd out
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DwxUSE_OPENGL=0 ..
        ninja
